# Generated by Django 2.1.7 on 2019-03-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190313_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category_images/'),
        ),
    ]
