# Generated by Django 2.1.7 on 2019-03-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190322_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='active_post',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived'), (4, 'Deactive')]),
        ),
    ]
