# Generated by Django 2.1.7 on 2019-03-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190323_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active_post',
            field=models.SmallIntegerField(choices=[(1, 'Taslak'), (2, 'Yayında'), (3, 'Arşivlendi'), (4, 'Kaldırıldı')], default='2'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.Category'),
        ),
    ]
