# Generated by Django 2.1.7 on 2019-03-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190325_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page_header_content',
            field=models.SmallIntegerField(choices=[(1, 'Big Box'), (2, 'First Small Box'), (3, 'Second Small Box'), (4, 'Other')]),
        ),
    ]
