# Generated by Django 2.1.7 on 2019-04-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190412_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page_header_content',
            field=models.SmallIntegerField(choices=[(1, 'Big Box'), (2, 'First Small Box'), (3, 'Second Small Box'), (4, 'Other')], default=4),
        ),
    ]
