# Generated by Django 2.1.7 on 2019-04-14 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190414_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sources',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='blog.SubCategory', verbose_name='Alt Kategori Adı'), to='blog.SubCategory'),
        ),
    ]
