"""
Django settings for kolayinibul project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1pvy#$=1f#%rq3*3wp!+g93hsxa*9h^hsdt&iq-&sejjgd^k+m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.kolayinibul.com', '127.0.0.1', '127.0.0.2', '127.0.0.1:8000']

# Application definition

INSTALLED_APPS = [
    #  Main
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',

    # Apps
    'blog',
    'user',
    'base_pages',
    'job',

    # 3rd Apps.
    'ckeditor',
    'django_extensions',
    'crispy_forms',
    'robots',
    'widget_tweaks',
    'social_django',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'kolayinibul.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base_pages.views.categories',
                'base_pages.views.footerpost',
                'base_pages.views.big_box',
                'base_pages.views.second_box',
                'base_pages.views.third_box',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',

            ],
        },
    },
]
ROBOTS_USE_SITEMAP = True
ROBOTS_SITEMAP_URLS = [
    'https://www.kolayinibul.com/sitemap.xml'
]
ROBOTS_SITEMAP_VIEW_NAME = 'cached-sitemap'
WSGI_APPLICATION = 'kolayinibul.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
CRISPY_TEMPLATE_PACK = 'uni-form'

CKEDITOR_CONFIGS = {
    "default": {
        "removePlugins": "stylesheetparser",
        "allowedContent": True,
        "width": "100%",
    },
    "special": {
        "toolbar": "Special",
        "toolbar_Special": [
            ['Bold'], ['CodeSnippet'],  # < here
        ],
        "extraPlugins": 'codesnippet',  # < here
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'index'
LOGIN_URL = '/user/login/'
LOGOUT_URL = '/user/logout/'

# Github Login Issues

SOCIAL_AUTH_GITHUB_KEY = '422b821bc5dcf3fa95f7'
SOCIAL_AUTH_GITHUB_SECRET = 'd171fed953f8d846a736624e2652ca70d8419986'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/my_profile/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/my_profile/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Yandex Mail SMTP Setup
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_USER = 'iletisim@kolayinibul.com'
EMAIL_HOST_PASSWORD = 'safsalak1'
DEFAULT_FROM_EMAIL = 'Kolayını Bul! <iletisim@kolayinibul.com>'
SERVER_EMAIL = 'iletisim@kolayinibul.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
