# Generated by Django 2.1.7 on 2019-03-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subcategory_category_name'),
        ('user', '0005_auto_20190313_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskills',
            name='skill_set',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='blog.SubCategory'),
        ),
        migrations.DeleteModel(
            name='UserSkills',
        ),
    ]
