# Generated by Django 2.1.7 on 2019-03-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190317_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='education',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Github Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='stack_overflow_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Stack Overflow Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter Profile'),
        ),
    ]
