# Generated by Django 2.1.7 on 2019-04-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190412_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/defaultuser.jpg', upload_to='avatars/'),
        ),
    ]
