# Generated by Django 2.1.7 on 2019-04-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190412_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Profile'),
        ),
    ]
