# Generated by Django 2.1.7 on 2019-04-15 20:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0015_auto_20190414_0448'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Firma Adı')),
                ('title', models.CharField(max_length=50, verbose_name='İş Başlığı')),
                ('slug', models.SlugField(blank=True, max_length=55, null=True)),
                ('description', ckeditor.fields.RichTextField(max_length=100000, verbose_name='İş Açıklaması')),
                ('company_logo', models.ImageField(blank=True, default='', null=True, upload_to='company_logos/')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('verified_date', models.DateTimeField(auto_now_add=True, verbose_name='Verified Date')),
                ('type', models.SmallIntegerField(choices=[(1, 'Firma'), (2, 'Bireysel')])),
                ('term', models.SmallIntegerField(choices=[(1, 'Kısa Dönem'), (2, 'Uzun Dönem'), (3, 'Tek Seferlik'), (4, 'Staj'), (5, 'Uzaktan Çalışma')])),
                ('job_status', models.SmallIntegerField(choices=[(1, 'Taslak'), (2, 'Yayında'), (3, 'Arşivlendi'), (4, 'Kaldırıldı'), (5, 'Onay Bekliyor')], default=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='blog.Category', verbose_name='Kategori Adı')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İşveren')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sub_category', to='blog.SubCategory', verbose_name='Alt Kategori Adı')),
                ('tag', models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sub_category', to='blog.SubCategory', verbose_name='Alt Kategori Adı'), to='blog.SubCategory')),
            ],
        ),
    ]
