# Generated by Django 2.1.7 on 2019-04-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvertisement',
            name='avg_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='email_adress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
